symptom_dataset = ['itching', 'skin rash', 'nodal skin eruptions',
                   'continuous sneezing', 'shivering', 'chills', 'joint pain',
                   'stomach pain', 'acidity', 'ulcers on tongue', 'muscle wasting',
                   'vomiting', 'burning micturition', 'spotting urination', 'fatigue',
                   'weight gain', 'anxiety', 'cold hands and feets', 'mood swings',
                   'weight loss', 'restlessness', 'lethargy', 'patches in throat',
                   'irregular sugar level', 'cough', 'high fever', 'sunken eyes',
                   'breathlessness', 'sweating', 'dehydration', 'indigestion',
                   'headache', 'yellowish skin', 'dark urine', 'nausea',
                   'loss of appetite', 'pain behind the eyes', 'back pain',
                   'constipation', 'abdominal pain', 'diarrhoea', 'mild fever',
                   'yellow urine', 'yellowing of eyes', 'acute liver failure',
                   'fluid overload', 'swelling of stomach', 'swelled lymph nodes',
                   'malaise', 'blurred and distorted vision', 'phlegm',
                   'throat irritation', 'redness of eyes', 'sinus pressure',
                   'runny nose', 'congestion', 'chest pain', 'weakness in limbs',
                   'fast heart rate', 'pain during bowel movements',
                   'pain in anal region', 'bloody stool', 'irritation in anus',
                   'neck pain', 'dizziness', 'cramps', 'bruising', 'obesity',
                   'swollen legs', 'swollen blood vessels', 'puffy face and eyes',
                   'enlarged thyroid', 'brittle nails', 'swollen extremeties',
                   'excessive hunger', 'extra marital contacts',
                   'drying and tingling lips', 'slurred speech', 'knee pain',
                   'hip joint pain', 'muscle weakness', 'stiff neck',
                   'swelling joints', 'movement stiffness', 'spinning movements',
                   'loss of balance', 'unsteadiness', 'weakness of one body side',
                   'loss of smell', 'bladder discomfort', 'foul smell ofurine',
                   'continuous feel of urine', 'passage of gases', 'internal itching',
                   'toxic look (typhos)', 'depression', 'irritability', 'muscle pain',
                   'altered sensorium', 'red spots over body', 'belly pain',
                   'abnormal menstruation', 'dischromic patches',
                   'watering from eyes', 'increased appetite', 'polyuria',
                   'family history', 'mucoid sputum', 'rusty sputum',
                   'lack of concentration', 'visual disturbances',
                   'receiving blood transfusion', 'receiving unsterile injections',
                   'coma', 'stomach bleeding', 'distention of abdomen',
                   'history of alcohol consumption', 'blood in sputum',
                   'prominent veins on calf', 'palpitations', 'painful walking',
                   'pus filled pimples', 'blackheads', 'scurring', 'skin peeling',
                   'silver like dusting', 'small dents in nails',
                   'inflammatory nails', 'blister', 'red sore around nose',
                   'yellow crust ooze',]

disease_index = {
    0: 'Fungal infection',
    1: 'Allergy',
    2: 'GERD',
    3: 'Chronic cholestasis',
    4: 'Drug Reaction',
    5: 'Peptic ulcer diseae',
    6: 'AIDS',
    7: 'Diabetes ',
    8: 'Gastroenteritis',
    9: 'Bronchial Asthma',
    10: 'Hypertension ',
    11: 'Migraine',
    12: 'Cervical spondylosis',
    13: 'Paralysis (brain hemorrhage)',
    14: 'Jaundice',
    15: 'Malaria',
    16: 'Chicken pox',
    17: 'Dengue',
    18: 'Typhoid',
    19: 'hepatitis A',
    20: 'Hepatitis B',
    21: 'Hepatitis C',
    22: 'Hepatitis D',
    23: 'Hepatitis E',
    24: 'Alcoholic hepatitis',
    25: 'Tuberculosis',
    26: 'Common Cold',
    27: 'Pneumonia',
    28: 'Dimorphic hemmorhoids(piles)',
    29: 'Heart attack',
    30: 'Varicose veins',
    31: 'Hypothyroidism',
    32: 'Hyperthyroidism',
    33: 'Hypoglycemia',
    34: 'Osteoarthristis',
    35: 'Arthritis',
    36: '(vertigo) Paroymsal  Positional Vertigo',
    37: 'Acne',
    38: 'UrUrinary tract infection',
    39: 'Psoriasis',
    40: 'Impetigo'
}
